- name: Play varaiable
  hosts: localhost
  vars:
   URL: play.example.com
  tasks:
   - name: print the varaibale
     ansible.builtin.debug:
      msg: URL = {{URL}}

- name: varaiable from file
  hosts: localhost
  vars_file:
    - var.yml 
  tasks:
   - name: print the varaibale from file
     ansible.builtin.debug:
      msg: URL = {{URL}}