- name: Play varaiable
  hosts: localhost
  vars:
   URL: play.example.com
  tasks:
   - name: print the varaibale from play
     ansible.builtin.debug:
      msg: URL = {{URL}}


- name: varaiable from file
  hosts: localhost
  #vars_file works only on play level
  vars_files:
    - var.yml 
  tasks:
   - name: print the varaibale from file
     ansible.builtin.debug:
      msg: URL = {{URL}}

- name: varaiable from task
  hosts: localhost
  tasks:
   - name: print the varaibale from task
     vars: ## these vars will access only in this task , in the same play next task cant access it
      URL: www.chatgpt.com
     ansible.builtin.debug:
      msg: URL = {{URL}}

- name: varaiable from inv file
  hosts: all
  tasks:
   - name: print the varaibale from inv file
     ansible.builtin.debug:
      msg: URL = {{URL}}

- name : Register a variable
  hosts: localhost
  tasks:
   - name: Getup time output
     ansible.builtin.shell: uptime
     register: out

   - name: print output
     ansible.builtin.debug:
      msg: "{{out}}"

   - name: Declare a variable
     ansible.builtin.set_facts:
       status: "{{out.rc}}"